logger:
  log_file_path: ../logs/log.txt
  debug: false
  max_size_mb: 10
  max_backups: 2
  max_age_days: 30
  local_time: true
  compress: true # архивирование при превышении лимита файла
db: # postgresql
  db_name: healthcheck
  db_host: localhost
  db_port: 5432
  db_user: postgres
  db_password: postgres
check_interval_sec: 10
server:
  port: 11000
